---
# install_puppet_server/tasks/main.yml

- name: 'Install on RockyLinux8'
  ansible.builtin.include_tasks: RockyLinux.yml
  when:
    - 'ansible_distribution == "Rocky"'
    - 'ansible_distribution_major_version == "8"'

- name: 'Install on AlmaLinux8'
  ansible.builtin.include_tasks: AlmaLinux.yml
  when:
    - 'ansible_distribution == "AlmaLinux"'
    - 'ansible_distribution_major_version == "8"'
